### ISSUE TITLE
Array not supporting minItems/maxItems

### ISSUE THREAD

**Issue by LucaWolf** [neotoolkit/dummy#327]
I wanted to implement this response: 
schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                minItems: 5
                maxItems: 10
where User schema took advantage of the x-faker fields. But only one item was returned in the response. 
How do I make it reply with an array or faker objects?

**Comment by LucaWolf** [comment]
OK, so it turns out the faker was statically build during the schema parsing. I ended up with this *ugly* solution (https://github.com/LucaWolf/dummy) which:
- enhanced the openapi and Array schemes  with min/max Items (range support)
- enhanced the Faker and Array schemes with aback reference to the faker object (dynamic range and value generetor)

**Comment by sashamelentyev** [comment]
> I wanted to implement this response: schema: type: array items: $ref: '#/components/schemas/User' minItems: 5 maxItems: 10 where User schema took advantage of the x-faker fields. But only one item was returned in the response. How do I make it reply with an array or faker objects?

Add support this soon
